# Generated by Django 4.1.9 on 2023-06-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soft_user_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='softuserproject',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
