# Generated by Django 4.1.9 on 2023-06-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soft_user_project', '0005_alter_softuserproject_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='softuserproject',
            name='deleted',
            field=models.CharField(default='Deleted', max_length=10),
        ),
    ]
