# Generated by Django 4.1.9 on 2023-06-09 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soft_user_project', '0006_softuserproject_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softuserproject',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='softuserproject',
            name='is_active',
        ),
    ]
