# Generated by Django 4.1.9 on 2023-06-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soft_user_project', '0007_remove_softuserproject_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='softuserproject',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
